# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-22 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191202_2259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_total',
            new_name='total',
        ),
    ]
